name: OpenTUMFlex_py37
channels:
  - conda-forge
  - defaults
dependencies:
  - appdirs=1.4.4=pyh9f0ad1d_0
  - blosc=1.20.1=ha925a31_0
  - bzip2=1.0.8=he774522_3
  - ca-certificates=2020.10.14=0
  - certifi=2020.11.8=py37haa95532_0
  - cycler=0.10.0=py_2
  - freetype=2.10.4=h546665d_0
  - glpk=4.65=h2fa13f4_1002
  - hdf5=1.10.6=nompi_h89124ea_1110
  - icu=67.1=h33f27b4_0
  - intel-openmp=2020.3=h57928b3_311
  - joblib=0.17.0=py_0
  - jpeg=9d=h8ffe710_0
  - kiwisolver=1.3.1=py37h8c56517_0
  - krb5=1.17.2=hbae68bd_0
  - libblas=3.9.0=3_blis
  - libcblas=3.9.0=3_blis
  - libclang=10.0.1=default_hf44288c_1
  - libcurl=7.71.1=h4b64cdc_8
  - liblapack=3.9.0=3_hd5c7e75_netlib
  - libpng=1.6.37=h1d00b33_2
  - libssh2=1.9.0=hb06d900_5
  - libtiff=4.1.0=hc10be44_6
  - lz4-c=1.9.2=h62dcd97_2
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - matplotlib=3.3.3=py37h03978a9_0
  - matplotlib-base=3.3.3=py37h3379fd5_0
  - mkl=2020.4=hb70f87d_311
  - mock=4.0.2=py37hc8dfbb8_1
  - msys2-conda-epoch=20160418=1
  - nose=1.3.7=py_1006
  - numexpr=2.7.1=py37h414f9d2_3
  - numpy=1.19.4=py37hd20adf4_1
  - olefile=0.46=pyh9f0ad1d_1
  - openpyxl=3.0.6=pyhd3eb1b0_0
  - openssl=1.1.1h=he774522_0
  - pandas=1.1.4=py37h08fd248_0
  - patsy=0.5.1=py_0
  - pillow=8.0.1=py37hdec93a9_0
  - pip=20.2.4=py_0
  - ply=3.11=py_1
  - pyomo=5.7.1=py37h1834ac0_1
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyqt=5.12.3=py37h1834ac0_4
  - pytables=3.6.1=py37h14417ae_3
  - python=3.7.9=h60c2a47_0
  - python-dateutil=2.8.1=py_0
  - python_abi=3.7=1_cp37m
  - pytz=2020.4=pyhd8ed1ab_0
  - pyutilib=6.0.0=pyh9f0ad1d_0
  - qt=5.12.9=hb2cf2c5_0
  - scipy=1.5.3=py37h6db1a17_0
  - seaborn=0.11.0=h57928b3_1
  - seaborn-base=0.11.0=pyhd8ed1ab_1
  - setuptools=49.6.0=py37hf50a25e_2
  - six=1.15.0=pyh9f0ad1d_0
  - spyder=4.1.5=py37_0
  - spyder-kernels=1.9.4=py37_0
  - sqlite=3.33.0=he774522_1
  - statsmodels=0.12.1=py37hda49f71_1
  - tk=8.6.10=he774522_1
  - tornado=6.1=py37hcc03f2d_0
  - tqdm=4.52.0=pyhd3deb0d_0
  - tzdata=2020d=h516909a_0
  - vc=14.1=h869be7e_1
  - vs2015_runtime=14.16.27012=h30e32a0_2
  - wheel=0.35.1=pyh9f0ad1d_0
  - wincertstore=0.2=py37hc8dfbb8_1005
  - xlrd=1.2.0=pyh9f0ad1d_1
  - xz=5.2.5=h62dcd97_1
  - zlib=1.2.11=h62dcd97_1010
  - zstd=1.4.5=h1f3a1b7_2
  - pip:
    - pyqt5-sip==4.19.18
    - pyqtchart==5.12
    - pyqtwebengine==5.12.1
